#!/bin/bash

# WiFi Configuration Helper for ESP32-S3 Wireless USB Disk
# This script helps you quickly configure WiFi settings

CONFIG_FILE="include/wifi_config.h"

echo "==================================================="
echo "ESP32-S3 Wireless USB Disk - WiFi Configuration"
echo "==================================================="
echo ""

# Check if config file exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: $CONFIG_FILE not found!"
    echo "Please run this script from the project root directory."
    exit 1
fi

# Show current configuration
echo "Current WiFi Configuration:"
echo "---------------------------------------------------"
grep "^#define DEFAULT_" "$CONFIG_FILE" | sed 's/#define /  /'
echo ""

echo "Choose configuration type:"
echo "1) Access Point Only (portable, works anywhere)"
echo "2) Home/Office WiFi + Access Point (recommended)"
echo "3) Home/Office WiFi Only (no access point)"
echo "4) Custom configuration"
echo "5) View examples and exit"
echo ""

read -p "Enter your choice (1-5): " choice

case $choice in
    1)
        echo ""
        echo "=== Access Point Only Configuration ==="
        read -p "Access Point name [wireless-usb-disk]: " ap_ssid
        ap_ssid=${ap_ssid:-wireless-usb-disk}
        
        read -p "Access Point password [12345678]: " ap_pass
        ap_pass=${ap_pass:-12345678}
        
        # Create new config
        cat > "$CONFIG_FILE" << EOF
/**
 * WiFi Configuration for ESP32-S3 Wireless USB Disk
 * Generated by configure_wifi.sh
 */

#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

#define DEFAULT_AP_SSID       "$ap_ssid"
#define DEFAULT_AP_PASSWORD   "$ap_pass"

#define DEFAULT_STA_SSID      ""
#define DEFAULT_STA_PASSWORD  ""
#define DEFAULT_WIFI_MODE     "AP"

#endif // WIFI_CONFIG_H
EOF
        
        echo ""
        echo "✓ Configured for Access Point only mode"
        echo "  Network: $ap_ssid"
        echo "  Password: $ap_pass"
        echo "  Access via: http://192.168.4.1"
        ;;
        
    2)
        echo ""
        echo "=== Home/Office WiFi + Access Point Configuration ==="
        read -p "Your WiFi network name: " sta_ssid
        read -p "Your WiFi password: " sta_pass
        
        read -p "Access Point name [wireless-usb-disk]: " ap_ssid
        ap_ssid=${ap_ssid:-wireless-usb-disk}
        
        read -p "Access Point password [12345678]: " ap_pass
        ap_pass=${ap_pass:-12345678}
        
        # Create new config
        cat > "$CONFIG_FILE" << EOF
/**
 * WiFi Configuration for ESP32-S3 Wireless USB Disk
 * Generated by configure_wifi.sh
 */

#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

#define DEFAULT_AP_SSID       "$ap_ssid"
#define DEFAULT_AP_PASSWORD   "$ap_pass"

#define DEFAULT_STA_SSID      "$sta_ssid"
#define DEFAULT_STA_PASSWORD  "$sta_pass"
#define DEFAULT_WIFI_MODE     "AP+STA"

#endif // WIFI_CONFIG_H
EOF
        
        echo ""
        echo "✓ Configured for dual mode (recommended)"
        echo "  Will connect to: $sta_ssid"
        echo "  Also creates: $ap_ssid"
        echo "  Access via: http://192.168.4.1 or your router's IP"
        ;;
        
    3)
        echo ""
        echo "=== Home/Office WiFi Only Configuration ==="
        read -p "Your WiFi network name: " sta_ssid
        read -p "Your WiFi password: " sta_pass
        
        # Create new config
        cat > "$CONFIG_FILE" << EOF
/**
 * WiFi Configuration for ESP32-S3 Wireless USB Disk
 * Generated by configure_wifi.sh
 */

#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

#define DEFAULT_AP_SSID       "wireless-usb-disk"
#define DEFAULT_AP_PASSWORD   "12345678"

#define DEFAULT_STA_SSID      "$sta_ssid"
#define DEFAULT_STA_PASSWORD  "$sta_pass"
#define DEFAULT_WIFI_MODE     "STA"

#endif // WIFI_CONFIG_H
EOF
        
        echo ""
        echo "✓ Configured for Station mode only"
        echo "  Will connect to: $sta_ssid"
        echo "  Access via: IP assigned by your router (check serial monitor)"
        ;;
        
    4)
        echo ""
        echo "=== Custom Configuration ==="
        read -p "Access Point name: " ap_ssid
        read -p "Access Point password: " ap_pass
        read -p "Your WiFi name (or leave empty): " sta_ssid
        if [ -n "$sta_ssid" ]; then
            read -p "Your WiFi password: " sta_pass
            echo "Choose mode:"
            echo "1) AP+STA (both networks)"
            echo "2) STA (your WiFi only)"
            read -p "Mode choice (1-2): " mode_choice
            if [ "$mode_choice" = "1" ]; then
                mode="AP+STA"
            else
                mode="STA"
            fi
        else
            sta_pass=""
            mode="AP"
        fi
        
        # Create new config
        cat > "$CONFIG_FILE" << EOF
/**
 * WiFi Configuration for ESP32-S3 Wireless USB Disk
 * Generated by configure_wifi.sh
 */

#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

#define DEFAULT_AP_SSID       "$ap_ssid"
#define DEFAULT_AP_PASSWORD   "$ap_pass"

#define DEFAULT_STA_SSID      "$sta_ssid"
#define DEFAULT_STA_PASSWORD  "$sta_pass"
#define DEFAULT_WIFI_MODE     "$mode"

#endif // WIFI_CONFIG_H
EOF
        
        echo ""
        echo "✓ Custom configuration applied"
        echo "  Mode: $mode"
        ;;
        
    5)
        echo ""
        echo "Please see WIFI_EXAMPLES.md for detailed configuration examples."
        exit 0
        ;;
        
    *)
        echo "Invalid choice. Exiting."
        exit 1
        ;;
esac

echo ""
echo "Next steps:"
echo "1. Build and flash: pio run -t upload"
echo "2. Insert SD card and power on"
echo "3. Device will use your pre-configured settings"
echo ""
echo "Note: You can always change settings later via the web interface."
