/**
 * WiFi Configuration for ESP32-S3 Wireless USB Disk
 * Generated by configure_wifi.sh
 */

#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

#define DEFAULT_AP_SSID       "brother-usb"
#define DEFAULT_AP_PASSWORD   "stopeatingmyface"

#define DEFAULT_STA_SSID      "Hail Satan"
#define DEFAULT_STA_PASSWORD  "stopeatingmyface"
#define DEFAULT_WIFI_MODE     "AP+STA"

#endif // WIFI_CONFIG_H
